services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akucantik
      POSTGRES_DB: attendance_db_v2
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  php-backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres_db

  python-service:
    build: ./python-service
    ports:
      - "5001:5000"
      - "9010:5000"
    env_file:
      - .env
    volumes:
      - ./python-service:/app
    depends_on:
      - postgres_db

volumes:
  postgres_data:
