services:
  postgres_db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  php-backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres_db

  python-service:
    build: ./python-service
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./python-service:/app
    depends_on:
      - postgres_db

volumes:
  postgres_data:
